class_name GoddessLines
extends Resource
## What the goddess says when you die. Copy lives in res://data/goddess/lines.tres, generated by tools/build_soul.gd, and is
## Sean's to edit. Her first words belong to the opening, not here.

## cause (a creature id, "spear" or "poison") -> Array of lines, cycled by death count.
@export var by_cause: Dictionary = {}
## Spoken instead of a cause line every `SoulRules.many_deaths` deaths.
@export var many_deaths: Array = []
## For a cause with no lines.
@export var fallback: String = ""

## The line for a death. `deaths` counts this one (SoulProgress.note_death runs first); `every` is SoulRules.many_deaths.
## First rule that applies: a many-deaths line on every `every`-th death; the cause's line at index `deaths` modulo its list;
## the fallback.
func line_for(cause: String, deaths: int, every: int) -> String:
	if every > 0 and deaths > 0 and deaths % every == 0 and not many_deaths.is_empty():
		@warning_ignore("integer_division")
		var turn := deaths / every - 1
		return str(many_deaths[posmod(turn, many_deaths.size())])
	var lines: Array = by_cause.get(cause, [])
	if not lines.is_empty():
		return str(lines[posmod(deaths, lines.size())])
	return fallback
