class_name OpeningDef
extends Resource
## The opening's copy and shape: the choices a truck offers, each truck's prompt and what every choice does to it, and her first
## words. Lives in res://data/opening/opening.tres (generated by tools/build_opening.gd; the lines are Sean's to rewrite).

## [{"id": String, "label": String}], the menu in order.
@export var choices: Array = []
## [{"prompt": String, "results": {choice id: the line shown when that choice meets this truck}}], one entry per truck.
@export var trucks: Array = []
## Shown for a choice a truck has no line for.
@export var fallback: String = ""
## Her first words, shown on top of her menu.
@export var goddess_line: String = ""

## The line for `choice_id` against truck `truck`: the truck's own, else the fallback (also for a truck that does not exist).
func result_for(truck: int, choice_id: String) -> String:
	if truck < 0 or truck >= trucks.size():
		return fallback
	var results = (trucks[truck] as Dictionary).get("results", {}) if typeof(trucks[truck]) == TYPE_DICTIONARY else {}
	if typeof(results) != TYPE_DICTIONARY:
		return fallback
	return str(results[choice_id]) if results.has(choice_id) else fallback
