class_name PerkDef
extends Resource
## A permanent upgrade sold at an altar for soul points, bought several times at a rising price. It applies from the next life.
## Content lives in res://data/perks/, generated by tools/build_soul.gd.

@export var id: String = ""
@export var display_name: String = ""
@export var description: String = ""
## The id of the altar that sells it.
@export var altar: String = ""
@export var price_base: int = 0
@export var price_step: int = 0
## [{"stat": String, "amount": int}]: what each purchase adds.
@export var effects: Array = []

## The price of the next purchase when `times_bought` have been made.
func price_of(times_bought: int) -> int:
	return price_base + price_step * times_bought
