class_name SoulRules
extends Resource
## The numbers of the soul layer, tuned by play. Content lives in res://data/soul/soul_rules.tres, generated by tools/build_soul.gd.

## Held essence of one element that buys one soul point at an altar (any element, the same rate).
@export var bank_rate: int = 10
## The price of the 1st, 2nd, ... starting level bought in the goddess's menu. Its length is the most levels that can be bought.
@export var level_prices: Array = [2, 3, 4, 5]
## What each owned power taken as a head start costs.
@export var power_price: int = 3
## Every this many deaths she speaks a many-deaths line instead of a cause line.
@export var many_deaths: int = 5
