class_name SpeciesDef
extends Resource
## A body the goddess can send you back as. Content lives in res://data/species/, generated by tools/build_soul.gd.

@export var id: String = ""
@export var display_name: String = ""
## An id under res://data/movement/, or "" for none.
@export var movement_profile: String = ""
## {"kind": "default"}, {"kind": "count", "creature": id, "n": int} (eaten or defeated n of it) or
## {"kind": "defeat", "creature": id} (one defeat of a rare creature or boss).
@export var unlock: Dictionary = {}
