class_name SkillDef
extends Resource
## One skill. Content lives in res://data/skills/, generated by tools/build_content.gd.

@export var id: String = ""
@export var display_name: String = ""
@export var description: String = ""
@export var hint: String = ""
@export var announce: String = ""
## proficiency | essence | evolution | enemy_only
@export var source: String = "proficiency"
@export var hidden: bool = true
@export var secret: bool = false
@export var starting: bool = false
## Conditions, all required (AND): counter / reset_counter / skill_level dictionaries.
@export var unlock: Array = []
## {"event": String, "tags": Dictionary}; counts only events after the unlock.
@export var levels_on: Dictionary = {}
@export var level_curve: int = 0
@export var max_level: int = 1
@export var effects: Array = []
@export var trigger: Dictionary = {}
## MP spent per cast of this skill's active effect (player skills only).
@export var mp_cost: int = 0
## The parent this evolution turns into: the branch key (siblings share it) and the active slot it takes over.
@export var replaces: String = ""
## What evolving this power costs, in held essence: element -> units. Set once on the base power; its evolution branches share
## it (they read it through `replaces`). Empty on every other skill.
@export var evolution_price: Dictionary = {}

## Event names whose arrival can change this skill's unlock or level.
func listens_to() -> Array:
	var out: Array = []
	for c in unlock:
		match c.get("kind", ""):
			"counter", "reset_counter":
				_add(out, c.get("event", ""))
			"skill_level":
				_add(out, Events.SKILL_UNLOCKED)
				_add(out, Events.SKILL_LEVELED)
	if not levels_on.is_empty():
		_add(out, levels_on.get("event", ""))
	return out

## Skills this one requires through skill_level conditions.
func parent_ids() -> Array:
	var out: Array = []
	for c in unlock:
		if c.get("kind", "") == "skill_level":
			out.append(c.get("id", ""))
	return out

## Essences referenced by `absorbed` counters in the unlock.
func essences_used() -> Array:
	var out: Array = []
	for c in unlock:
		if c.get("event", "") == Events.ABSORBED and c.get("tags", {}).has("essence"):
			_add(out, c["tags"]["essence"])
	return out

## Creature ids named by `predated` counters in the unlock ("eat a spider"), for the Compendium hint and the unlock wording.
func sources_used() -> Array:
	var out: Array = []
	for c in unlock:
		if c.get("event", "") == Events.PREDATED and c.get("tags", {}).has("source"):
			_add(out, c["tags"]["source"])
	return out

static func _add(list: Array, value: String) -> void:
	if value != "" and not list.has(value):
		list.append(value)
